// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: order/v1/order.proto

package orderv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderStreamService_SubscribeToOrderUpdates_FullMethodName = "/order.v1.OrderStreamService/SubscribeToOrderUpdates"
)

// OrderStreamServiceClient is the client API for OrderStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStreamServiceClient interface {
	SubscribeToOrderUpdates(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderStatusUpdate], error)
}

type orderStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStreamServiceClient(cc grpc.ClientConnInterface) OrderStreamServiceClient {
	return &orderStreamServiceClient{cc}
}

func (c *orderStreamServiceClient) SubscribeToOrderUpdates(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OrderStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderStreamService_ServiceDesc.Streams[0], OrderStreamService_SubscribeToOrderUpdates_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OrderRequest, OrderStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderStreamService_SubscribeToOrderUpdatesClient = grpc.ServerStreamingClient[OrderStatusUpdate]

// OrderStreamServiceServer is the server API for OrderStreamService service.
// All implementations must embed UnimplementedOrderStreamServiceServer
// for forward compatibility.
type OrderStreamServiceServer interface {
	SubscribeToOrderUpdates(*OrderRequest, grpc.ServerStreamingServer[OrderStatusUpdate]) error
	mustEmbedUnimplementedOrderStreamServiceServer()
}

// UnimplementedOrderStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStreamServiceServer struct{}

func (UnimplementedOrderStreamServiceServer) SubscribeToOrderUpdates(*OrderRequest, grpc.ServerStreamingServer[OrderStatusUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToOrderUpdates not implemented")
}
func (UnimplementedOrderStreamServiceServer) mustEmbedUnimplementedOrderStreamServiceServer() {}
func (UnimplementedOrderStreamServiceServer) testEmbeddedByValue()                            {}

// UnsafeOrderStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStreamServiceServer will
// result in compilation errors.
type UnsafeOrderStreamServiceServer interface {
	mustEmbedUnimplementedOrderStreamServiceServer()
}

func RegisterOrderStreamServiceServer(s grpc.ServiceRegistrar, srv OrderStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStreamService_ServiceDesc, srv)
}

func _OrderStreamService_SubscribeToOrderUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderStreamServiceServer).SubscribeToOrderUpdates(m, &grpc.GenericServerStream[OrderRequest, OrderStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderStreamService_SubscribeToOrderUpdatesServer = grpc.ServerStreamingServer[OrderStatusUpdate]

// OrderStreamService_ServiceDesc is the grpc.ServiceDesc for OrderStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.OrderStreamService",
	HandlerType: (*OrderStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToOrderUpdates",
			Handler:       _OrderStreamService_SubscribeToOrderUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order/v1/order.proto",
}
